{"version":3,"sources":["errorHandler.test.js"],"names":["errorHandler","require","describe","it","err","Error","res","status","jest","mockReturnThis","send","fn","toHaveBeenCalledWith","expect","error"],"mappings":"aAAA,IAAMA,aAAeC,QAAQ,4BAA7BC,SAAMF,eAAeC,WAGnBE,GAAG,oDAAqD,WAD1DD,IAASE,EAAA,IAAAC,MAAgB,cACpBC,EAAA,CACDC,OAAYC,KAAIH,KAAMI,iBACtBC,KAASF,KAAGG,MAEVD,aAAWC,EAAL,KAAAL,EAAA,MAERN,OAAAA,EAAAA,QAAkBY,qBAAlB,KAEAC,OAAOP,EAAIC,MAALK,qBAAaA,CAAqBE,MAAxC","file":"errorHandler.test.min.js","sourcesContent":["const errorHandler = require('../../utils/errorHandler');\r\n\r\ndescribe('errorHandler', () => {\r\n  it('should return a 500 status code and error message', () => {\r\n    const err = new Error('Test error');\r\n    const res = {\r\n      status: jest.fn().mockReturnThis(),\r\n      send: jest.fn(),\r\n    };\r\n    errorHandler(err, null, res, null);\r\n\r\n    expect(res.status).toHaveBeenCalledWith(500);\r\n    expect(res.send).toHaveBeenCalledWith({ error: 'Test error' });\r\n  });\r\n});\r\n"]}